### ISSUE TITLE
multiple images, from 1 link

### ISSUE THREAD

**Issue by nickfmc** [hphaavikko/dimbox#1]
script looks nice so far! Is there a way to have a gallery of images triggered from 1 text link, like "view gallery" that opens the images

**Comment by hphaavikko** [comment]
Thx! At the moment only solution for that would be to have all the links with the same data-dimbox attribute value in the page dom. They could of course be hidden, so you just wrap them in a hidden div or something and have only the one link visible. Something like this:

```
<a href="my-awesome-img-1.jpg" data-dimbox="my-awesome-gallery">Open gallery</a>

<div class="visually-hidden">
    <a href="my-awesome-img-2.jpg" data-dimbox="my-awesome-gallery">Img 2</a>
    <a href="my-awesome-img-3.jpg" data-dimbox="my-awesome-gallery">Img 3</a>
    <a href="my-awesome-img-4.jpg" data-dimbox="my-awesome-gallery">Img 4</a>
    <a href="my-awesome-img-5.jpg" data-dimbox="my-awesome-gallery">Img 5</a>
</div>
```

So it can done pretty easily imo.
