### ISSUE TITLE
Pressing the escape key to close dim box does not work

### ISSUE THREAD

**Issue by ashishb** [hphaavikko/dimbox#10]
Pressing the escape key to close dim box does not work, is it possible to add this?

**Comment by hphaavikko** [comment]
Good point! Pressing esc closes fullscreen mode but not the box itself. Will add this in the next update, thanks!

**Comment by hphaavikko** [comment]
Added closing DimBox on esc press in [v1.1.1](https://github.com/hphaavikko/dimbox/releases/tag/v1.1.1)

**Comment by ashishb** [comment]
Thanks
