### ISSUE TITLE
Request to Add Parameters to DimBox Methods: onBeforeUpdateContent, onAfterUpdateContent, onContentLoaded

### ISSUE THREAD

**Issue by mokrys** [hphaavikko/dimbox#11]
Hello, thank you for your library. DimBox is an excellent tool! I would like to ask if it’s possible to add parameters to the methods onBeforeUpdateContent, onAfterUpdateContent, or onContentLoaded. I am missing a parameter that indicates which content (e.g., an ID or some other data) is being loaded. Would it be possible to include such a parameter?

**Comment by hphaavikko** [comment]
Yea, that's a good idea! Will look into it as soon as I can.

**Comment by hphaavikko** [comment]
Alrighty, in v1.1.4 a reference to the current a element is passed as an argument to callback function calls onBeforeUpdateContent, onAfterUpdateContent and onContentLoaded. The actual content being loaded you can of course get from the a elements href attribute.
