### ISSUE TITLE
Add data-dimbox-download Attribute

### ISSUE THREAD

**Issue by mokrys** [hphaavikko/dimbox#12]
I propose adding a data-dimbox-download attribute to allow for easier file downloads for inline type or other. This attribute would store the file URL for download. Thank you.

**Comment by hphaavikko** [comment]
Good idea this one too, will look into this one as well as soon as I can.

**Comment by hphaavikko** [comment]
Alrighty, this is added in version 1.1.3. The attribute name is data-dimbox-download-file though, just to be clear that it sets the file to be downloaded, not true/false to show the download button or not.
