### ISSUE TITLE
Accessibility and focus

### ISSUE THREAD

**Issue by PionerJn** [hphaavikko/dimbox#2]
Hi there! Love your little dimbox.

I would suggest a good improvement would be to trap focus inside the "modal" so TAB only travels through buttons inside it. As an example: https://micromodal.vercel.app/

Was reading this (https://dev.to/islam/how-to-trap-focus-inside-a-modal-2791) but I'm not js savy enough to modify your dimbox to do this.

**Comment by hphaavikko** [comment]
Yea, that's a good idea. Will do that, not sure when but as soon as possible.

**Comment by hphaavikko** [comment]
Alrighty, focus trapping added in v1.0.3.
