### ISSUE TITLE
YouTube autoplay

### ISSUE THREAD

**Issue by bpmarine** [hphaavikko/dimbox#6]
Hi there,

Really enjoying using your elegant plugin. I realise that YouTube videos are basically iframes as ooposed to true video types, but I wonder if you've had any success with getting autoplay to work with the href url or other method. I have tried &autoplay=1, etc.

I can't see anything in your code that deals with this. Wondering if you had any experience with the youtube_api methods for this effect.

Any thoughts appreciated

**Comment by hphaavikko** [comment]
It should work normally, there's nothing in DimBox (or at least shouldn't be) that could affect the autoplay. Notice however that autoplay doesn't work on some mobile browsers and even the major desktop browsers have had it disabled: https://stackoverflow.com/questions/58189735/embedded-youtube-iframes-no-longer-autoplay Dunno what's the status now though. Anyways, this shouldn't be a DimBox issue but I will check it just in case as soon as I have time.

**Comment by bpmarine** [comment]
Thanks @hphaavikko . I found that the allow="autoplay;" attribute I was passing to the href link with .setAttribute is being overridden by the Dimbox iframe template, even though it accepts the data-dimbox attributes set in the same way. As a quick hack I added the allow="autoplay;" to the dimbox.js iframe template and it autoplays as expected. I will either work out how to properly target the dimbox iframe with setAttribute or use your custom template method which seems like it will be ideal for this as well.

**Comment by bpmarine** [comment]
Custom template worked perfectly. No issue - thanks for the prompt which made me try harder!

**Comment by hphaavikko** [comment]
Yea it seems in an iframe the autoplay will work only if parameter mute=1 is set also: https://developer.chrome.com/blog/autoplay/

**Comment by bpmarine** [comment]
Thanks

I haven't seen that necessity, working well in Dimbox now without it.

Best regards
Brandon
