### ISSUE TITLE
Stop from snapping to clicked link.

### ISSUE THREAD

**Issue by Eric-Nims** [hphaavikko/dimbox#7]
I have a button, at the bottom of the page. I click it and a form pops up. Everything works great but when I close the popup, it snaps back down to the bottom of the site. Is there a way to stop this and just close the popup and stay where it is in the site?

**Comment by hphaavikko** [comment]
Are you saying the pages scroll position changes when closing dimbox? It shouldn't do that and I have not encountered such problem. Can you link to the page or demo where the problem occurs?

**Comment by Eric-Nims** [comment]
Hi,

 
Thank you for the response. You can do it on your demo page. Put the raptor image at the bottom and have it half under the bottom of the site, like the image below. You’ll see that when you close dimbox, the page scrolls to show the whole raptor image.

 

 
After you close dimbox

 

So, if I have the link like in the image below, in the footer, after I close dimbox, it scrolls to the bottom of the page.


 
Thank You,

 
Eric Nims

Software Developer

***@***.*** ***@***.***> 

 

 
Web: lifeexpertnow.com

Member Website: mylifeexpert.com


A Simply BETTER Work/Life SOLUTION

 
CONFIDENTIALITY NOTICE: This email message is intended only for the party or entity addressed. It may contain information that is confidential, not to be disclosed. Anyone receiving this email other than the intended party is hereby notified that dissemination, distribution, or copying of the communication is prohibited. If you receive this email in error, please notify us using the contact information provided above.

**Comment by hphaavikko** [comment]
You're right Eric, so it does! I'm not sure if it's a feature I did on purpose or not :D But I'll look into it when I have the time. Good observation!

**Comment by Eric-Nims** [comment]
Awesome, thank you so much!

 
Thank You,

 
Eric Nims

Software Developer

***@***.*** ***@***.***> 

 

 
Web: lifeexpertnow.com

Member Website: mylifeexpert.com


A Simply BETTER Work/Life SOLUTION

 
CONFIDENTIALITY NOTICE: This email message is intended only for the party or entity addressed. It may contain information that is confidential, not to be disclosed. Anyone receiving this email other than the intended party is hereby notified that dissemination, distribution, or copying of the communication is prohibited. If you receive this email in error, please notify us using the contact information provided above.

**Comment by hphaavikko** [comment]
Ookay, so this is what's really happening there:

1. When DimBox is opened, focus is trapped inside DimBox. So if the user uses keyboard and moves in clickable elements with tab key, the focus goes around DimBox elements only, not the actual page under it.
2. When DimBox is closed the focus is set back to the element which was clicked to open DimBox.
3. Focusing the element causes the browser to scroll to element, so if the element is only partially visible the broswer scrolls so it'll be fully visible.

This should be an easy fix with the focus method preventScrolling option: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus I'll try to fix it as soon as possible.

**Comment by hphaavikko** [comment]
Alrighty, this is now fixed in v1.0.4.

**Comment by Eric-Nims** [comment]
You are awesome, ty

Get Outlook for Android <https://aka.ms/AAb9ysg> 
--------------------------------

**Comment by Eric-Nims** [comment]
You are the man, thank you!

 
Thank You,

 
Eric Nims

Software Developer

***@***.*** ***@***.***> 

 

 
Web: lifeexpertnow.com

Member Website: mylifeexpert.com


A Simply BETTER Work/Life SOLUTION

 
CONFIDENTIALITY NOTICE: This email message is intended only for the party or entity addressed. It may contain information that is confidential, not to be disclosed. Anyone receiving this email other than the intended party is hereby notified that dissemination, distribution, or copying of the communication is prohibited. If you receive this email in error, please notify us using the contact information provided above.

**Comment by Eric-Nims** [comment]
Worked like a champ!!! TY so much!

**Comment by hphaavikko** [comment]
No worries!
