### ISSUE TITLE
Download External Images loaded in dimbox

### ISSUE THREAD

**Issue by coldes** [hphaavikko/dimbox#8]
Hello, first of all a great job with creating dimbox. Was having a play in codepen and for images was using images from my codepen assets resource, which meant images were "external" urls. When trying the "download" function, images were opening in a new tab rather than downloading. Trying the dimbox demo site, downloading an image works. I then proceded to adding a simple demo of dimbox on my server, and yes, an image on my sever [in demo folder] when displayed in dimbox does download, however an "external" url image same problem of opening in a new tab. Looking at the .dimbox-btn-download element that is created, then yes made sense as to why an "external" url image won't download. So I decided it would be good to allow for both images (server hosted or an external hosted image(s) [subject to any cors]). Downloaded your full JS code and proceded to figure out a how to. Have come up with the following that seems to work. You may want to consider incorporating this, and any improvement of my attempt. From line 399 in dimbox.js
```
function updateDownloadButton() {
	if (!config.showDownloadButton) {
		return;
	}
	// Check if download button exists in DOM already
	if (dimboxContainer.querySelector('.dimbox-btn-download')) {
		// Update href right away
		downloadBtn.href = currentEl.href;
		// Current type is not image or video...
		if (currentType !== 'image' && currentType !== 'video') {
			// ...so remove download button from the DOM
			dimboxContainer.removeChild(downloadBtn);
			downloadBtn = null;
		}
	} else if (currentType === 'image' || currentType === 'video') {
		// Download button does not exits yet, create it
		//console.log(currentEl.href);
		var imgSrc = currentEl.href;
		var hostname = window.location.hostname;
		//console.log(hostname);
		if (imgSrc.includes(hostname)) {
			console.log("my server image");
			downloadBtn = document.createElement('a');
			downloadBtn.className = 'dimbox-btn-download';
			downloadBtn.innerHTML = config.svgDownloadButton;
			downloadBtn.href = currentEl.href;
			downloadBtn.target = '_blank';
			downloadBtn.setAttribute('download', '');
			dimboxContainer.appendChild(downloadBtn);
			downloadBtn.addEventListener('click', function() {
				executeCallback('onDownload');
			});
		} else if (!imgSrc.includes(hostname)) {
			console.log("external image");
			downloadBtn = document.createElement('a');
			downloadBtn.className = 'dimbox-btn-download';
			downloadBtn.innerHTML = config.svgDownloadButton;
			downloadBtn.href = currentEl.href;
			downloadBtn.target = '_blank';
			downloadBtn.setAttribute('download', '');
			dimboxContainer.appendChild(downloadBtn);
			function downloadImage(event) {
				event.preventDefault();
				var url = currentEl.href;
				var fileName = url.match(/([^\/]+)$/)[1];
				//console.log(fileName);
				fetch(url)
					.then(function(response) {
						return response.blob();
					})
					.then(function(blob) {
						var url = window.URL.createObjectURL(blob);
						var a = document.createElement('a');
						a.style.display = 'none';
						a.href = url;
						a.download = fileName;
						document.body.appendChild(a);
						a.click();
						window.URL.revokeObjectURL(url);
						document.body.removeChild(a);
					})
					.then(function() {
						executeCallback('onDownload');
					}).catch(function() {
						alert('An error sorry')
					});
			}
			downloadBtn.addEventListener('click', downloadImage);
		}
		//NOTE see onBeforeUpdateContent: function()
	} //end else if
}
```
Then in dimbox.setConfig I needed to add the following to allow for mixed server hosted images and external hosted images:
```
dimbox.setConfig({
    onBeforeUpdateContent: function() {
	if(document.querySelector('.dimbox-btn-download')){
            document.querySelector('.dimbox-btn-download').remove();
	}
    }
});
```
On a side note, on demo site,  type:ajax does not work (https://api.punkapi.com/v2/beers/random). Could you updated/fix as am interest to see how this renders.

I look forward to your response, thank you, Col

**Comment by hphaavikko** [comment]
Yea the download attribute works only for same origin urls: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#download Your suggested workaround could be a nice solution (but preferrably should be done without any extra config, should be doable), will look into that.

It seem's that Brewdog's Punk API is down, I hope it's temporary since it's fun data to use in examples. If they have put it down for good have to find some other funny api to use :D

**Comment by hphaavikko** [comment]
Alrighty, support for cross-domain downloads is added in v1.0.5. Please note that Access-Control-Allow-Origin header must be set on the remote server to allow download. If not, then CORS policy will block the download and the file is opened in a new tab like before.

I'll create a separate issue of th ajax examples.
